"""add_source_file_path_to_user_resumes

Revision ID: 485ef4294586
Revises: 63be29bcddb9
Create Date: 2025-11-17 10:51:51.218849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485ef4294586'
down_revision = '63be29bcddb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resumes', sa.Column('source_file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resumes', 'source_file_path')
    # ### end Alembic commands ###


