"""add_parsed_resume_table

Revision ID: 63be29bcddb9
Revises: c65d06169be9
Create Date: 2025-11-11 07:37:43.302264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63be29bcddb9'
down_revision = 'c65d06169be9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_resumes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('parsed_data', sa.JSON(), nullable=False),
        sa.Column('raw_text', sa.Text(), nullable=True),
        sa.Column('source_file_name', sa.String(length=255), nullable=True),
        sa.Column('source_file_type', sa.String(length=100), nullable=True),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('validation', sa.JSON(), nullable=True),
        sa.Column('correction', sa.JSON(), nullable=True),
        sa.Column('quality_analysis', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_resumes_id'), 'parsed_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_resumes_user_id'), 'parsed_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_resumes_user_id'), table_name='parsed_resumes')
    op.drop_index(op.f('ix_parsed_resumes_id'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    # ### end Alembic commands ###


