"""add_template_usage_count

Revision ID: c65d06169be9
Revises: c6e85d67e90b
Create Date: 2025-11-10 13:31:03.652611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65d06169be9'
down_revision = 'c6e85d67e90b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_templates', sa.Column('usage_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_templates', 'usage_count')
    # ### end Alembic commands ###


