"""add_template_version_management

Revision ID: c6e85d67e90b
Revises: c5895f9af329
Create Date: 2025-11-10 13:20:34.331866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e85d67e90b'
down_revision = 'c5895f9af329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加版本管理字段到 resume_templates 表
    op.add_column('resume_templates', sa.Column('version', sa.String(length=50), server_default='1.0.0', nullable=True))
    op.add_column('resume_templates', sa.Column('parent_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_resume_templates_parent', 'resume_templates', 'resume_templates', ['parent_template_id'], ['id'])
    
    # 创建 template_versions 表
    op.create_table('template_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('version_name', sa.String(length=255), nullable=True),
        sa.Column('template_schema', sa.JSON(), nullable=False),
        sa.Column('style_config', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['resume_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_versions_id'), 'template_versions', ['id'], unique=False)
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_constraint('fk_resume_templates_parent', 'resume_templates', type_='foreignkey')
    op.drop_column('resume_templates', 'parent_template_id')
    op.drop_column('resume_templates', 'version')
    # ### end Alembic commands ###


